// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itirbcfmzkoxubvvjorp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0aXJiY2ZtemtveHVidnZqb3JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyODU4NzgsImV4cCI6MjA1ODg2MTg3OH0.vjG1L3FngtS_Fyv3FT7pUF35g4CMzJlElQsq0GqPwY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);